name: "Defang Deployment Action"
description: "Use defang to automatically deploy your application to the cloud."
author: "Defang"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  cliVersion: 
    description: "The version of the defang CLI to use."
    required: false
    default: "latest"
  args:
    description: "The arguments to pass to the defang CLI."
    required: false
    default: "compose up"

runs:
  using: "composite"
  steps:
    - name: Install defang
      shell: bash
      run: . <(curl -Ls https://s.defang.io/install)

    - name: Login to Defang
      shell: bash
      run: | 
        defang login
        defang whoami

    # We shouldn't need this once env var support is in.
    # - name: Deploy Config
    #   shell: bash
    #   run: ${{ github.action_path }}/config.sh
    #   working-directory: ${{ inputs.directory }}

    - name: Execute
      shell: bash
      run: |
        if [[ "${DEFANG_INTERNAL_TEST}" == "dfng-test" ]]; then
          defang compose config
        else
          defang ${{ inputs.args }}
        fi
      working-directory: ${{ inputs.directory }}
