name: "Defang Deployment Action"
description: "Use defang to automatically deploy your application to the cloud."
author: "Defang"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  cli-version:
    description: "The version of the Defang CLI to use."
    required: false
    default: ""
  config-env-vars:
    description: "Environment variables deploy as config. Format: 'VAR1 VAR2 VAR3'"
    required: false
    default: ""
  cwd:
    description: "The directory containing the compose file to deploy."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install defang
      shell: bash
      run: . <(curl -Ls https://s.defang.io/install)
      env:
        DEFANG_CLI_VERSION: ${{ inputs['cli-version'] }}

    - name: Login to Defang
      shell: bash
      run: | 
        defang login
        defang whoami

    - name: Deploy Config
      shell: bash
      run: ${{ github.action_path }}/config.sh
      working-directory: ${{ inputs.cwd }}
      env:
        CONFIG_ENV_VARS: ${{ inputs['config-env-vars'] }}

    - name: Execute
      shell: bash
      run: |
        if [[ "${DEFANG_INTERNAL_TEST}" == "dfng-test" ]]; then
          defang compose config
        else
          defang compose up
        fi
      working-directory: ${{ inputs.cwd }}
