name: "Defang Deployment Action"
description: "Use Defang to automatically deploy your application to the cloud."
author: "DefangLabs"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  cli-version:
    description: "The version of the Defang CLI to use. Defaults to the latest stable release."
    required: false
    default: ""
  config-env-vars:
    description: "Environment variables deploy as config. Format: 'VAR1 VAR2 VAR3'"
    required: false
    default: ""
  command:
    description: "The command to run."
    required: false
    default: "compose up"
  compose-files:
    description: "The compose files to deploy. Format 'file1 file2 file3'"
    required: false
    default: ""
  cwd:
    description: "The directory containing the compose file to deploy."
    required: false
    default: "."
  mode:
    description: "The deployment mode. Options: 'development', 'staging', 'production'"
    required: false
    default: ""
  provider:
    description: "The cloud provider to deploy to. Options: 'aws', 'defang', 'digitalocean', 'gcp'"
    required: false
    default: "defang"
  verbose:
    description: "Enable verbose output for debugging."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install defang
      shell: bash
      run: . <(curl -Lf https://raw.githubusercontent.com/DefangLabs/defang/main/src/bin/install || echo return $?)
      env:
        DEFANG_INSTALL_VERSION: ${{ inputs['cli-version'] }}
        GH_TOKEN: ${{ github.token }} # avoid rate-limits

    - name: Set Defang environment variables
      shell: bash
      run: |
        echo "DEFANG_PROVIDER=${{ inputs['provider'] }}" >> $GITHUB_ENV
        [ -n "$RUNNER_DEBUG" ] && echo "DEFANG_DEBUG=$RUNNER_DEBUG" >> $GITHUB_ENV || true

    - name: Login to Defang
      shell: bash
      run: |
        defang login
        defang whoami

    - name: Defang Config Set
      shell: bash
      if: ${{ inputs['config-env-vars'] != '' }}
      run: |
        # Iterate over the sources and set the environment variables
        params=()
        for filename in $COMPOSE_FILES; do
            params+=("-f")
            params+=("$filename")
        done
        for source in $CONFIG_ENV_VARS; do
          echo "Updating $source"
          echo defang config "${params[@]}" set -e $source
          defang config "${params[@]}" set -e $source
        done
      working-directory: ${{ inputs.cwd }}
      env:
        COMPOSE_FILES: ${{ inputs['compose-files'] }}
        CONFIG_ENV_VARS: ${{ inputs['config-env-vars'] }}

    - name: Defang ${{ inputs['command'] }}
      if: ${{ inputs['command'] != '' }}
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: |
        params=()
        for filename in $COMPOSE_FILES; do
            params+=("-f")
            params+=("$filename")
        done
        if [[ -n "${{ inputs['mode'] }}" ]]; then
          params+=("--mode=${{ inputs['mode'] }}")
        fi

        case "${{ inputs['verbose'] }}" in
          y|Y|yes|Yes|YES|true|True|TRUE|on|On|ON|1) params+=("--verbose") ;;
        esac

        echo defang $COMMAND "${params[@]}"
        defang $COMMAND "${params[@]}"
      env:
        COMMAND: ${{ inputs['command'] }}
        COMPOSE_FILES: ${{ inputs['compose-files'] }}
