name: "Defang Deployment Action"
description: "Use Defang to automatically deploy your application to the cloud."
author: "Defang"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  cli-version:
    description: "The version of the Defang CLI to use."
    required: false
    default: ""
  config-env-vars:
    description: "Environment variables deploy as config. Format: 'VAR1 VAR2 VAR3'"
    required: false
    default: ""
  cwd:
    description: "The directory containing the compose file to deploy."
    required: false
    default: "."
  compose-files:
    description: "The compose files to deploy. Format 'file1 file2 file3'"
    required: false
    default: ""
  behavior:
    description: "The behavior of the deployment. Options: 'development', 'staging', 'production'"
    required: false
    default: "development"

runs:
  using: "composite"
  steps:
    - name: Install defang
      shell: bash
      run: . <(curl -Ls https://s.defang.io/install)
      env:
        DEFANG_INSTALL_VERSION: ${{ inputs['cli-version'] }}

    - name: Login to Defang
      shell: bash
      run: | 
        defang login
        defang whoami

    - name: Deploy Config
      shell: bash
      run: ${{ github.action_path }}/config.sh
      working-directory: ${{ inputs.cwd }}
      env:
        CONFIG_ENV_VARS: ${{ inputs['config-env-vars'] }}

    - name: Execute
      shell: bash
      run: |
        params=()
        for filename in ${{ inputs['compose-files'] }}; do
            params+=("-f")
            params+=("$filename")
        done
        if [[ -n "${{ inputs['behavior'] }}" ]]; then
          params+=("--behavior=${{ inputs['behavior'] }}")
        fi

        if [[ "${DEFANG_INTERNAL_TEST}" == "dfng-test" ]]; then
          # `defang compose up --dry-run` is used for testing as --behavior flag is only available to the "compose up" command
          echo defang compose "${params[@]}" up --dry-run
          defang compose "${params[@]}" up --dry-run
        else
          echo defang compose "${params[@]}" up
          defang compose "${params[@]}" up
        fi
      working-directory: ${{ inputs.cwd }}
